- name: Setup .files
  tags:
    - dot-files
  vars:
    dot_dir: "{{ lookup('env', 'HOME') }}/.dot-files"
  block:

    - name: Clone dot-files
      command: gh repo clone dot-files {{ dot_dir }}

    - name: Stow dot-files
      shell:
        cmd: "make reset && make"
        chdir: "{{ dot_dir }}"

    - name: mamba init
      shell: zsh /root/mambaforge/bin/conda init

