- name: Setup GitHub CLI
  tags:
    - core
    - gh
  block:

    - name: Check if repository file exists
      stat:
        path: /etc/apt/sources.list.d/github-cli.list
      register: repo_file

    - name: Download GitHub CLI GPG key
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
        force: false
      register: gpg_key

    - name: Add GitHub CLI repository to sources.list
      lineinfile:
        dest: /etc/apt/sources.list.d/github-cli.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        create: yes
      when: repo_file.stat.exists == false

    - name: Install gh
      become: true
      apt:
        update_cache: true
        name: gh
